version: '3.6'
services:
  mongo:
    image: mongo:4.4 # Later versions require CPU with AVX support
    container_name: unifi-mongo
    networks:
      - unifi
    restart: always
    volumes:
      - ./volumes/mongo:/data/db
  unifi:
    image: "jacobalberty/unifi:${TAG:-latest}"
    container_name: unifi
    depends_on:
      - mongo
    networks:
      - unifi
    restart: always
    volumes:
      - ./volumes/unifi:/unifi
    user: unifi
    sysctls:
      net.ipv4.ip_unprivileged_port_start: 0
    environment:
      DB_URI: mongodb://mongo/unifi
      STATDB_URI: mongodb://mongo/unifi_stat
      DB_NAME: unifi
    ports:
      - "3478:3478/udp" # STUN
      - "6789:6789/tcp" # Speed test
      - "80:8080/tcp" # Device/ controller comm.
      - "443:8443/tcp" # Controller GUI/API as seen in a web browser
#      - "8880:8880/tcp" # HTTP portal redirection
#      - "8843:8843/tcp" # HTTPS portal redirection
      - "10001:10001/udp" # AP discovery
networks:
  unifi:
